console.log(1)
console.log(2)
console.log(3)
console.log(4)
console.log(5)
setTimeout(() => {console.log("Network call 01")}, 2000)
console.log(6)
console.log(7)
console.log(8)
console.log(9)
console.log(10)
setTimeout(() => {console.log("Network call 02")}, 1000)